### ISSUE TITLE
Move Kerwin's scripts into Qualitas

### ISSUE THREAD

**Issue by m1yag1** [openstax/quality-assurance-meta#79]
Kerwin has built a number of scripts and dashboards that help him conduct his day to day operations. Due to the fact that he is leaving it's best to move these somewhere else we can maintain them. We'll move the scripts over to qualitas-server and ask DevOps for a proper server instead of using Heroku.

## Acceptance Criteria

- [x] Use Heroku Scheduler to keep qualitas server alive during working hours
- [x] Make request to devops for new server
- [ ] Develop ansible playbook for deployment
- [x] [Move cnx-repository dashboard](https://github.com/openstax/qualitas-server/issues/9)
- [x] [Move urlcommands dashboard](https://github.com/openstax/qualitas-server/issues/6)
- [x] [Move JSON Loader dashboard](https://github.com/openstax/qualitas-server/issues/7)

**Comment by m1yag1** [comment]
Closing b/c we'll probably stick with heroku for a long time.
