### ISSUE TITLE
How do I know my content published?

### ISSUE THREAD

**Issue by pumazi** [openstax/quality-assurance-meta#91]
## Story
As a developer/tester, I want to know when publications are made, so that I can verify work as it is happening.

The goal for this is to know when content has changed either through ones own actions or another. Knowing this information will provide a first step in investigating changes to the environment.

This will aid in testing because you'll be able to introspect what the system is doing on the inside before the results hit the outside world.

## Tasks

- [ ] implement a way to 'pub' publication events (result could be printing stdout a list of events in real-time)
- [ ] implement a 'sub' to write the event to a Slack channel (i.e. `#[<env>-]content-stream`)
- [ ] deploy solution ...somewhere?

## Nice-to-have

- N/A

## Acceptance Criteria

- a user can subscribe to watch a stream of publication events (e.g. slack)
