### ISSUE TITLE
Evaluate Concourse as a possible replacement for Jenkins

### ISSUE THREAD

**Issue by m1yag1** [openstax/quality-assurance-meta#96]
### Description

Unified will be evaluating ConcourseCI to run automated tasks and so will the QA team in order to see if it can replace Jenkins.

### Rationale

Jenkins is a great swiss army knife capable of many things but also comes with a very large learning curve. There are bugs that exist in Jenkins that don't look like they'll be fixed soon which requires potentially opening up security holes or require building a custom plugin. Tom Woodward has looked into Concourse and it looks like a good alternative to Jenkins. The continuous testing environment is CI agnostic so should continue to operate essentially the same as it did in Jenkins.

### Key Results

- [x] 100% of the training has been completed by M. Mulich and M. Arbelaez.
- [ ] Key jobs that exist in Jenkins have been ported over to Concourse.
- [ ] Evaluated the use of Concourse as an alternative to Jenkins.
